import { type NextPage } from "next";
import Head from "next/head";

const Login: NextPage = () => {
  return(
    <>
      <Head>
        <title>KroTalk</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-white">
        
      </main>
    </>
  )
}

export default Login